#!/bin/bash
echo -e ''
echo -e '                \033[0;37m*\033[0m\033[0;32m             '
echo -e '                    \033[0;32m.- '\''MMHHMM'\'' -.'
echo -e '                 .oH":HH$'\'' "'\'' '\'' -*R&o,     \033[0;37m*\033[0m'
echo -e '                \033[0;32mdMMM*""'\''`'\''      .oM"HM?.'
echo -e '              ,MMM'\''          "HLbd< ?&H \             '
echo -e '             \033[0;32m.:MH ."\          ` MM  MM&b'
echo -e '             "*H    -         &MMMMMMMMMH:                   '
echo -e '            \033[0;32m:    dboo        MMMMMMMMMMMM.	'
echo -e '            . .dMMMMMMb       *MMMMMMMMM '\'''
echo -e '    \033[0;32m        '\''  MMMMMMMP         *MMMMMP. '\'''
echo -e '             '\''    `MMMP"            HM* ,'
echo -e '     \033[0;32m         '\''    :MM              .- , '
echo -e '         \033[0;97m*\033[0m\033[0;32m     '\''.   `#?..  .         ..              '
echo -e '              \033[0;32m    -.   .         s .-'
echo -e '                     '\'''\''-.oo,oo.-'\'''\''\033[0m \033[1;32mjNet: It'\''s world wilde.\033[0m'
echo -e ''

 
