#!/bin/bash
echo -e ''                                                                                       
echo -e '\033[1;33m             @@@@@@@@   '            
echo -e '          @@          @@          ' 
echo -e '        @  @          @  @        '  
echo -e '      @  @@@@        @@@@  @      '  
echo -e '     @ @@@@@@@      @@@@@@@ @     '  
echo -e '       @@@@@@@@    @@@@@@@@       '  
echo -e '    @ @@@@@@@@ @@@@ @@@@@@@@ @    '  
echo -e '    @          @@@@          @    '
echo -e '     @                      @     '  
echo -e '     @        @@@@@@        @     '
echo -e '      @      @@@@@@@@      @      '  
echo -e '       @@   @@@@@@@@@@   @@       '  
echo -e '          @@          @@          ' 
echo -e '             @@@@@@@@             ' 
echo -e '                       \033[1;32mjNet: No TOXIC waste.\033[0m'                                               
echo -e ''                                                                            
